# Site settings
title: 'Glyphette'
description: 'Hand Lettering / Illustration / Art Direction by Anna Dutton'
url: 'http://glyphette.com'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'anna dutton'
  email: annaedutton@gmail.com
  linkedin_username: annaedutton
  behance_username: annaedutton
  # github_username: annaedutton
  # drupal_username: annaedutton
  # twitter_username: annaedutton
  # facebook_username: annaedutton
  # squarespace_username: annadutton

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
